//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IribDiplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class АнализРентабельности
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public АнализРентабельности()
        {
            this.АнализрентабельностивПроцентах = new HashSet<АнализрентабельностивПроцентах>();
            this.ДинамикаПроизводительностиТруда = new HashSet<ДинамикаПроизводительностиТруда>();
            this.ОценкаВаловогоДохода = new HashSet<ОценкаВаловогоДохода>();
            this.ФакторныйАнализПрибыли = new HashSet<ФакторныйАнализПрибыли>();
        }
    
        public int Год { get; set; }
        public Nullable<long> ПрибыльОтПродаж { get; set; }
        public Nullable<long> ПрибыльДоНалогообложения { get; set; }
        public Nullable<long> ЧистаяПрибыль { get; set; }
        public Nullable<long> ВыручкаОтПродаж { get; set; }
        public Nullable<long> СредняяСтоимостьАктивов { get; set; }
        public Nullable<long> СобственныйКапитал { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<АнализрентабельностивПроцентах> АнализрентабельностивПроцентах { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДинамикаПроизводительностиТруда> ДинамикаПроизводительностиТруда { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОценкаВаловогоДохода> ОценкаВаловогоДохода { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФакторныйАнализПрибыли> ФакторныйАнализПрибыли { get; set; }
    }
}
