//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IribDiplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class АнализрентабельностивПроцентах
    {
        public Nullable<double> ЭкономическкаяРентабельность { get; set; }
        public Nullable<double> БухгалтерскаяРентабельность { get; set; }
        public Nullable<double> РентабельностьСобственногоКапитала { get; set; }
        public Nullable<double> КоэффицентКапитализации { get; set; }
        public Nullable<double> ОборачиваемостьАктивов { get; set; }
        public Nullable<int> RentabYearID { get; set; }
        public int ID { get; set; }
    
        public virtual АнализРентабельности АнализРентабельности { get; set; }
    }
}
