//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IribDiplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДинамикаПроизводительностиТруда
    {
        public int ID { get; set; }
        public Nullable<int> IDYearWorkPerf { get; set; }
        public Nullable<int> ОбъемРабот { get; set; }
        public Nullable<int> Контингент { get; set; }
        public Nullable<int> ГодовойФондОплатыТруда { get; set; }
        public Nullable<int> СреднемесячнаяОплатТруда { get; set; }
        public Nullable<double> ПроизводительностьТруда { get; set; }
    
        public virtual АнализРентабельности АнализРентабельности { get; set; }
    }
}
