//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IribDiplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОценкаВаловогоДохода
    {
        public int Id { get; set; }
        public Nullable<int> IDYearincome { get; set; }
        public Nullable<int> Товарооборот { get; set; }
        public Nullable<int> ВаловойДоход { get; set; }
        public Nullable<double> УровеньВаловогоДоходаТоварообороту { get; set; }
        public Nullable<int> СебестоимостьТоваров { get; set; }
        public Nullable<int> УровеньВаловогоДоходаКСебес { get; set; }
        public Nullable<int> ИздержкиОбращения { get; set; }
        public Nullable<double> УрВалДоходаКИздерж { get; set; }
    
        public virtual АнализРентабельности АнализРентабельности { get; set; }
    }
}
