//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IribDiplom.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ФакторныйАнализПрибыли
    {
        public Nullable<int> FactoryYearID { get; set; }
        public string ВидПродукции { get; set; }
        public Nullable<long> КолвоРеализПродукции { get; set; }
        public Nullable<long> СредняяРеализПродукции { get; set; }
        public Nullable<long> СебестоимостьПродукции { get; set; }
        public Nullable<long> ИзменениеСуммыПрибыли { get; set; }
        public int ID { get; set; }
    
        public virtual АнализРентабельности АнализРентабельности { get; set; }
    }
}
